/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *eventbox89;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *eventbox5;
  GtkWidget *fixed2;
  GtkWidget *entrynom;
  GtkWidget *entryprenom;
  GtkWidget *entryID;
  GtkWidget *entrymdp;
  GtkWidget *entryadresse;
  GtkWidget *entryemail;
  GtkWidget *entrymatricule;
  GtkWidget *entrytype;
  GtkObject *day_adj;
  GtkWidget *day;
  GtkObject *month_adj;
  GtkWidget *month;
  GtkObject *year_adj;
  GtkWidget *year;
  GtkWidget *eventbox1;
  GtkWidget *labelnomm;
  GtkWidget *labelmdpm;
  GtkWidget *eventbox8;
  GtkWidget *radiobuttonfemme;
  GSList *radiobuttonfemme_group = NULL;
  GtkWidget *eventbox9;
  GtkWidget *labeltypedevoiture;
  GtkWidget *eventbox10;
  GtkWidget *labeldate_de_naissace;
  GtkWidget *eventbox14;
  GtkWidget *labelnom;
  GtkWidget *eventbox15;
  GtkWidget *labelprenom;
  GtkWidget *eventbox16;
  GtkWidget *labelID;
  GtkWidget *eventbox17;
  GtkWidget *labelmotdepasse;
  GtkWidget *eventbox18;
  GtkWidget *labeladresse;
  GtkWidget *eventbox19;
  GtkWidget *labelemail;
  GtkWidget *eventbox20;
  GtkWidget *labelsexe;
  GtkWidget *eventbox22;
  GtkWidget *label6;
  GtkWidget *eventbox24;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *eventbox25;
  GtkWidget *image1;
  GtkWidget *eventbox23;
  GtkWidget *label16;
  GtkWidget *eventbox26;
  GtkWidget *label45;
  GtkWidget *eventbox69;
  GtkWidget *labelmatricule;
  GtkWidget *eventbox85;
  GtkWidget *radiobuttonhomme;
  GtkWidget *eventbox95;
  GtkWidget *labelprenomm;
  GtkWidget *eventbox96;
  GtkWidget *labelidm;
  GtkWidget *eventbox97;
  GtkWidget *label39;
  GtkWidget *eventbox98;
  GtkWidget *label40;
  GtkWidget *eventbox99;
  GtkWidget *label41;
  GtkWidget *image10;
  GtkWidget *eventbox64;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entrynom1;
  GtkWidget *entryprenom1;
  GtkWidget *entryID1;
  GtkWidget *entryemail1;
  GtkWidget *entryadresse1;
  GtkWidget *entrymatricule1;
  GtkWidget *entrymotdepasse1;
  GtkWidget *entrytypedevoiture1;
  GtkObject *day1_adj;
  GtkWidget *day1;
  GtkObject *month1_adj;
  GtkWidget *month1;
  GtkObject *year1_adj;
  GtkWidget *year1;
  GtkWidget *eventbox27;
  GtkWidget *labelnom1;
  GtkWidget *eventbox28;
  GtkWidget *labelprenom1;
  GtkWidget *eventbox29;
  GtkWidget *labelID1;
  GtkWidget *eventbox30;
  GtkWidget *labeldatedenaissance1;
  GtkWidget *eventbox34;
  GtkWidget *labelemail1;
  GtkWidget *eventbox35;
  GtkWidget *labeladressse1;
  GtkWidget *eventbox36;
  GtkWidget *labelmatricule1;
  GtkWidget *eventbox37;
  GtkWidget *labelsexe1;
  GtkWidget *eventbox38;
  GtkWidget *labelmotdepasse1;
  GtkWidget *eventbox39;
  GtkWidget *labeltypedevoiture1;
  GtkWidget *eventbox41;
  GtkWidget *buttonmodifier;
  GtkWidget *eventbox40;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label29;
  GtkWidget *eventbox44;
  GtkWidget *label17;
  GtkWidget *eventbox90;
  GtkWidget *radiobuttonfemme1;
  GSList *radiobuttonfemme1_group = NULL;
  GtkWidget *eventbox91;
  GtkWidget *radiobuttonhomme1;
  GtkWidget *eventbox92;
  GtkWidget *label42;
  GtkWidget *eventbox93;
  GtkWidget *label43;
  GtkWidget *eventbox94;
  GtkWidget *label44;
  GtkWidget *image6;
  GtkWidget *eventbox63;
  GtkWidget *label2;
  GtkWidget *eventbox78;
  GtkWidget *fixed4;
  GtkWidget *eventbox70;
  GtkWidget *comboboxentry1;
  GtkWidget *eventbox72;
  GtkWidget *labelID2;
  GtkWidget *eventbox76;
  GtkWidget *actualiser;
  GtkWidget *eventbox77;
  GtkWidget *label30;
  GtkWidget *eventbox87;
  GtkWidget *buttonsuprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *eventbox75;
  GtkWidget *image3;
  GtkWidget *eventbox74;
  GtkWidget *label33;
  GtkWidget *entrymdp2;
  GtkWidget *eventbox88;
  GtkWidget *labelmdp;
  GtkWidget *image7;
  GtkWidget *eventbox62;
  GtkWidget *label3;
  GtkWidget *eventbox47;
  GtkWidget *fixed5;
  GtkWidget *entryID3;
  GtkWidget *entrymotdepasse3;
  GtkWidget *treeview1;
  GtkWidget *eventbox45;
  GtkWidget *labelID3;
  GtkWidget *eventbox46;
  GtkWidget *labelmotdepasse3;
  GtkWidget *eventbox48;
  GtkWidget *buttonafficher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *eventbox50;
  GtkWidget *image4;
  GtkWidget *eventbox49;
  GtkWidget *label37;
  GtkWidget *eventbox83;
  GtkWidget *label34;
  GtkWidget *image8;
  GtkWidget *eventbox61;
  GtkWidget *label4;
  GtkWidget *eventbox52;
  GtkWidget *fixed6;
  GtkWidget *entryID4;
  GtkWidget *entrymotdepasse4;
  GtkWidget *eventbox51;
  GtkWidget *label38;
  GtkWidget *eventbox53;
  GtkWidget *labelmotdepasse4;
  GtkWidget *eventbox54;
  GtkWidget *labelID4;
  GtkWidget *eventbox55;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *eventbox57;
  GtkWidget *image5;
  GtkWidget *eventbox56;
  GtkWidget *labelvalider;
  GtkWidget *eventbox58;
  GtkWidget *labelfa;
  GtkWidget *eventbox84;
  GtkWidget *tot;
  GtkWidget *image9;
  GtkWidget *eventbox60;
  GtkWidget *label5;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  eventbox89 = gtk_event_box_new ();
  gtk_widget_show (eventbox89);
  gtk_container_add (GTK_CONTAINER (window1), eventbox89);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (eventbox89), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 688, 680);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox5);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (eventbox5), fixed2);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynom, 128, 40);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenom, 128, 72);
  gtk_widget_set_size_request (entryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  entryID = gtk_entry_new ();
  gtk_widget_show (entryID);
  gtk_fixed_put (GTK_FIXED (fixed2), entryID, 128, 112);
  gtk_widget_set_size_request (entryID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID), 8226);

  entrymdp = gtk_entry_new ();
  gtk_widget_show (entrymdp);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymdp, 128, 144);
  gtk_widget_set_size_request (entrymdp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp), 8226);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed2), entryadresse, 128, 184);
  gtk_widget_set_size_request (entryadresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entryemail = gtk_entry_new ();
  gtk_widget_show (entryemail);
  gtk_fixed_put (GTK_FIXED (fixed2), entryemail, 128, 216);
  gtk_widget_set_size_request (entryemail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail), 8226);

  entrymatricule = gtk_entry_new ();
  gtk_widget_show (entrymatricule);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymatricule, 128, 280);
  gtk_widget_set_size_request (entrymatricule, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymatricule), 8226);

  entrytype = gtk_entry_new ();
  gtk_widget_show (entrytype);
  gtk_fixed_put (GTK_FIXED (fixed2), entrytype, 128, 312);
  gtk_widget_set_size_request (entrytype, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytype), 8226);

  day_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  day = gtk_spin_button_new (GTK_ADJUSTMENT (day_adj), 1, 0);
  gtk_widget_show (day);
  gtk_fixed_put (GTK_FIXED (fixed2), day, 184, 344);
  gtk_widget_set_size_request (day, 60, 27);

  month_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month = gtk_spin_button_new (GTK_ADJUSTMENT (month_adj), 1, 0);
  gtk_widget_show (month);
  gtk_fixed_put (GTK_FIXED (fixed2), month, 304, 344);
  gtk_widget_set_size_request (month, 60, 27);

  year_adj = gtk_adjustment_new (1, 1900, 2024, 1, 10, 10);
  year = gtk_spin_button_new (GTK_ADJUSTMENT (year_adj), 1, 0);
  gtk_widget_show (year);
  gtk_fixed_put (GTK_FIXED (fixed2), year, 432, 344);
  gtk_widget_set_size_request (year, 60, 27);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox1, 424, 32);
  gtk_widget_set_size_request (eventbox1, 144, 32);

  labelnomm = gtk_label_new ("");
  gtk_widget_show (labelnomm);
  gtk_container_add (GTK_CONTAINER (eventbox1), labelnomm);
  gtk_widget_set_size_request (labelnomm, 144, 32);

  labelmdpm = gtk_label_new ("");
  gtk_widget_show (labelmdpm);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmdpm, 0, 8);
  gtk_widget_set_size_request (labelmdpm, 253, 141);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox8, 112, 248);
  gtk_widget_set_size_request (eventbox8, 104, 24);

  radiobuttonfemme = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobuttonfemme);
  gtk_container_add (GTK_CONTAINER (eventbox8), radiobuttonfemme);
  gtk_widget_set_size_request (radiobuttonfemme, 104, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemme), radiobuttonfemme_group);
  radiobuttonfemme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemme));

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox9, 0, 312);
  gtk_widget_set_size_request (eventbox9, 120, 24);

  labeltypedevoiture = gtk_label_new (_("type de voiture"));
  gtk_widget_show (labeltypedevoiture);
  gtk_container_add (GTK_CONTAINER (eventbox9), labeltypedevoiture);
  gtk_widget_set_size_request (labeltypedevoiture, 120, 24);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox10, 0, 352);
  gtk_widget_set_size_request (eventbox10, 128, 17);

  labeldate_de_naissace = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (labeldate_de_naissace);
  gtk_container_add (GTK_CONTAINER (eventbox10), labeldate_de_naissace);
  gtk_widget_set_size_request (labeldate_de_naissace, 128, 17);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox14, 8, 40);
  gtk_widget_set_size_request (eventbox14, 96, 24);

  labelnom = gtk_label_new (_("nom"));
  gtk_widget_show (labelnom);
  gtk_container_add (GTK_CONTAINER (eventbox14), labelnom);
  gtk_widget_set_size_request (labelnom, 96, 24);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox15, 0, 72);
  gtk_widget_set_size_request (eventbox15, 96, 25);

  labelprenom = gtk_label_new (_("prenom"));
  gtk_widget_show (labelprenom);
  gtk_container_add (GTK_CONTAINER (eventbox15), labelprenom);
  gtk_widget_set_size_request (labelprenom, 96, 25);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox16, 0, 120);
  gtk_widget_set_size_request (eventbox16, 81, 16);

  labelID = gtk_label_new (_("ID"));
  gtk_widget_show (labelID);
  gtk_container_add (GTK_CONTAINER (eventbox16), labelID);
  gtk_widget_set_size_request (labelID, 81, 16);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox17, 0, 152);
  gtk_widget_set_size_request (eventbox17, 104, 17);

  labelmotdepasse = gtk_label_new (_("mot de passe"));
  gtk_widget_show (labelmotdepasse);
  gtk_container_add (GTK_CONTAINER (eventbox17), labelmotdepasse);
  gtk_widget_set_size_request (labelmotdepasse, 104, 17);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox18, 8, 192);
  gtk_widget_set_size_request (eventbox18, 97, 16);

  labeladresse = gtk_label_new (_("adresse"));
  gtk_widget_show (labeladresse);
  gtk_container_add (GTK_CONTAINER (eventbox18), labeladresse);
  gtk_widget_set_size_request (labeladresse, 97, 16);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox19, 0, 224);
  gtk_widget_set_size_request (eventbox19, 97, 17);

  labelemail = gtk_label_new (_("email"));
  gtk_widget_show (labelemail);
  gtk_container_add (GTK_CONTAINER (eventbox19), labelemail);
  gtk_widget_set_size_request (labelemail, 97, 17);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox20, 0, 248);
  gtk_widget_set_size_request (eventbox20, 88, 17);

  labelsexe = gtk_label_new (_("sexe"));
  gtk_widget_show (labelsexe);
  gtk_container_add (GTK_CONTAINER (eventbox20), labelsexe);
  gtk_widget_set_size_request (labelsexe, 88, 17);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 136, 8);
  gtk_widget_set_size_request (eventbox22, 176, 24);

  label6 = gtk_label_new (_("<u><span  font_size=\"15000\" > <span foreground=\"brown\">--Ajouter citoyen--</span></span></u>"));
  gtk_widget_show (label6);
  gtk_container_add (GTK_CONTAINER (eventbox22), label6);
  gtk_widget_set_size_request (label6, 176, 24);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 208, 400);
  gtk_widget_set_size_request (eventbox24, 104, 29);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_container_add (GTK_CONTAINER (eventbox24), buttonAjouter);
  gtk_widget_set_size_request (buttonAjouter, 104, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox25, FALSE, FALSE, 0);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (eventbox25), image1);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox23, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox23), label16);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 128, 440);
  gtk_widget_set_size_request (eventbox26, 368, 96);

  label45 = gtk_label_new (_("<span  font_size=\"35000\" > <span foreground=\"brown\">--Bienvenue!--</span></span>"));
  gtk_widget_show (label45);
  gtk_container_add (GTK_CONTAINER (eventbox26), label45);
  gtk_widget_set_size_request (label45, 368, 96);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox69, 0, 280);
  gtk_widget_set_size_request (eventbox69, 80, 24);

  labelmatricule = gtk_label_new (_("matricule"));
  gtk_widget_show (labelmatricule);
  gtk_container_add (GTK_CONTAINER (eventbox69), labelmatricule);
  gtk_widget_set_size_request (labelmatricule, 80, 24);

  eventbox85 = gtk_event_box_new ();
  gtk_widget_show (eventbox85);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox85, 216, 248);
  gtk_widget_set_size_request (eventbox85, 80, 24);

  radiobuttonhomme = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobuttonhomme);
  gtk_container_add (GTK_CONTAINER (eventbox85), radiobuttonhomme);
  gtk_widget_set_size_request (radiobuttonhomme, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhomme), radiobuttonfemme_group);
  radiobuttonfemme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhomme));

  eventbox95 = gtk_event_box_new ();
  gtk_widget_show (eventbox95);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox95, 424, 72);
  gtk_widget_set_size_request (eventbox95, 145, 32);

  labelprenomm = gtk_label_new ("");
  gtk_widget_show (labelprenomm);
  gtk_container_add (GTK_CONTAINER (eventbox95), labelprenomm);
  gtk_widget_set_size_request (labelprenomm, 145, 32);

  eventbox96 = gtk_event_box_new ();
  gtk_widget_show (eventbox96);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox96, 424, 112);
  gtk_widget_set_size_request (eventbox96, 147, 33);

  labelidm = gtk_label_new ("");
  gtk_widget_show (labelidm);
  gtk_container_add (GTK_CONTAINER (eventbox96), labelidm);
  gtk_widget_set_size_request (labelidm, 147, 33);

  eventbox97 = gtk_event_box_new ();
  gtk_widget_show (eventbox97);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox97, 128, 344);
  gtk_widget_set_size_request (eventbox97, 49, 22);

  label39 = gtk_label_new (_("Day:"));
  gtk_widget_show (label39);
  gtk_container_add (GTK_CONTAINER (eventbox97), label39);
  gtk_widget_set_size_request (label39, 49, 22);

  eventbox98 = gtk_event_box_new ();
  gtk_widget_show (eventbox98);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox98, 248, 344);
  gtk_widget_set_size_request (eventbox98, 50, 24);

  label40 = gtk_label_new (_("Month:"));
  gtk_widget_show (label40);
  gtk_container_add (GTK_CONTAINER (eventbox98), label40);
  gtk_widget_set_size_request (label40, 50, 24);

  eventbox99 = gtk_event_box_new ();
  gtk_widget_show (eventbox99);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox99, 368, 344);
  gtk_widget_set_size_request (eventbox99, 54, 25);

  label41 = gtk_label_new (_("Year:"));
  gtk_widget_show (label41);
  gtk_container_add (GTK_CONTAINER (eventbox99), label41);
  gtk_widget_set_size_request (label41, 54, 25);

  image10 = create_pixmap (window1, "IMG_1902.jpeg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed2), image10, 0, 0);
  gtk_widget_set_size_request (image10, 696, 648);

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), eventbox64);

  label1 = gtk_label_new (_("<span  font_size=\"13000\" > <span foreground=\"brown\">Ajouter </span></span>"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox64), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entrynom1 = gtk_entry_new ();
  gtk_widget_show (entrynom1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynom1, 120, 32);
  gtk_widget_set_size_request (entrynom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom1), 8226);

  entryprenom1 = gtk_entry_new ();
  gtk_widget_show (entryprenom1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprenom1, 120, 64);
  gtk_widget_set_size_request (entryprenom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom1), 8226);

  entryID1 = gtk_entry_new ();
  gtk_widget_show (entryID1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryID1, 120, 96);
  gtk_widget_set_size_request (entryID1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID1), 8226);

  entryemail1 = gtk_entry_new ();
  gtk_widget_show (entryemail1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryemail1, 120, 160);
  gtk_widget_set_size_request (entryemail1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail1), 8226);

  entryadresse1 = gtk_entry_new ();
  gtk_widget_show (entryadresse1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryadresse1, 120, 192);
  gtk_widget_set_size_request (entryadresse1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse1), 8226);

  entrymatricule1 = gtk_entry_new ();
  gtk_widget_show (entrymatricule1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrymatricule1, 120, 224);
  gtk_widget_set_size_request (entrymatricule1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymatricule1), 8226);

  entrymotdepasse1 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrymotdepasse1, 120, 280);
  gtk_widget_set_size_request (entrymotdepasse1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse1), 8226);

  entrytypedevoiture1 = gtk_entry_new ();
  gtk_widget_show (entrytypedevoiture1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrytypedevoiture1, 120, 312);
  gtk_widget_set_size_request (entrytypedevoiture1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytypedevoiture1), 8226);

  day1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  day1 = gtk_spin_button_new (GTK_ADJUSTMENT (day1_adj), 1, 0);
  gtk_widget_show (day1);
  gtk_fixed_put (GTK_FIXED (fixed3), day1, 240, 128);
  gtk_widget_set_size_request (day1, 60, 27);

  month1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month1 = gtk_spin_button_new (GTK_ADJUSTMENT (month1_adj), 1, 0);
  gtk_widget_show (month1);
  gtk_fixed_put (GTK_FIXED (fixed3), month1, 360, 128);
  gtk_widget_set_size_request (month1, 60, 27);

  year1_adj = gtk_adjustment_new (1, 1900, 2024, 1, 10, 10);
  year1 = gtk_spin_button_new (GTK_ADJUSTMENT (year1_adj), 1, 0);
  gtk_widget_show (year1);
  gtk_fixed_put (GTK_FIXED (fixed3), year1, 488, 128);
  gtk_widget_set_size_request (year1, 69, 27);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox27, 24, 48);
  gtk_widget_set_size_request (eventbox27, 49, 17);

  labelnom1 = gtk_label_new (_("nom"));
  gtk_widget_show (labelnom1);
  gtk_container_add (GTK_CONTAINER (eventbox27), labelnom1);
  gtk_widget_set_size_request (labelnom1, 49, 17);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox28, 8, 80);
  gtk_widget_set_size_request (eventbox28, 72, 17);

  labelprenom1 = gtk_label_new (_("prenom"));
  gtk_widget_show (labelprenom1);
  gtk_container_add (GTK_CONTAINER (eventbox28), labelprenom1);
  gtk_widget_set_size_request (labelprenom1, 72, 17);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox29, 8, 104);
  gtk_widget_set_size_request (eventbox29, 49, 17);

  labelID1 = gtk_label_new (_("ID"));
  gtk_widget_show (labelID1);
  gtk_container_add (GTK_CONTAINER (eventbox29), labelID1);
  gtk_widget_set_size_request (labelID1, 49, 17);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox30, 0, 136);
  gtk_widget_set_size_request (eventbox30, 136, 16);

  labeldatedenaissance1 = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (labeldatedenaissance1);
  gtk_container_add (GTK_CONTAINER (eventbox30), labeldatedenaissance1);
  gtk_widget_set_size_request (labeldatedenaissance1, 136, 16);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox34, 8, 168);
  gtk_widget_set_size_request (eventbox34, 49, 17);

  labelemail1 = gtk_label_new (_("email"));
  gtk_widget_show (labelemail1);
  gtk_container_add (GTK_CONTAINER (eventbox34), labelemail1);
  gtk_widget_set_size_request (labelemail1, 49, 17);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox35, 8, 200);
  gtk_widget_set_size_request (eventbox35, 72, 16);

  labeladressse1 = gtk_label_new (_("adresse"));
  gtk_widget_show (labeladressse1);
  gtk_container_add (GTK_CONTAINER (eventbox35), labeladressse1);
  gtk_widget_set_size_request (labeladressse1, 72, 16);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox36, 8, 232);
  gtk_widget_set_size_request (eventbox36, 80, 17);

  labelmatricule1 = gtk_label_new (_("matricule"));
  gtk_widget_show (labelmatricule1);
  gtk_container_add (GTK_CONTAINER (eventbox36), labelmatricule1);
  gtk_widget_set_size_request (labelmatricule1, 80, 17);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox37, 0, 256);
  gtk_widget_set_size_request (eventbox37, 49, 17);

  labelsexe1 = gtk_label_new (_("sexe"));
  gtk_widget_show (labelsexe1);
  gtk_container_add (GTK_CONTAINER (eventbox37), labelsexe1);
  gtk_widget_set_size_request (labelsexe1, 49, 17);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox38, 0, 288);
  gtk_widget_set_size_request (eventbox38, 112, 17);

  labelmotdepasse1 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (labelmotdepasse1);
  gtk_container_add (GTK_CONTAINER (eventbox38), labelmotdepasse1);
  gtk_widget_set_size_request (labelmotdepasse1, 112, 17);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox39, 0, 321);
  gtk_widget_set_size_request (eventbox39, 120, 16);

  labeltypedevoiture1 = gtk_label_new (_("type de voiture"));
  gtk_widget_show (labeltypedevoiture1);
  gtk_container_add (GTK_CONTAINER (eventbox39), labeltypedevoiture1);
  gtk_widget_set_size_request (labeltypedevoiture1, 120, 16);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox41, 128, 360);
  gtk_widget_set_size_request (eventbox41, 112, 37);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_container_add (GTK_CONTAINER (eventbox41), buttonmodifier);
  gtk_widget_set_size_request (buttonmodifier, 112, 37);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), eventbox40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (eventbox40), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox2), label29, FALSE, FALSE, 0);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox44, 64, 0);
  gtk_widget_set_size_request (eventbox44, 264, 32);

  label17 = gtk_label_new (_("<u><span  font_size=\"15000\" > <span foreground=\"brown\">--Modifier citoyen--</span></span></u>"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox44), label17);
  gtk_widget_set_size_request (label17, 264, 32);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  eventbox90 = gtk_event_box_new ();
  gtk_widget_show (eventbox90);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox90, 120, 256);
  gtk_widget_set_size_request (eventbox90, 80, 24);

  radiobuttonfemme1 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobuttonfemme1);
  gtk_container_add (GTK_CONTAINER (eventbox90), radiobuttonfemme1);
  gtk_widget_set_size_request (radiobuttonfemme1, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemme1), radiobuttonfemme1_group);
  radiobuttonfemme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemme1));

  eventbox91 = gtk_event_box_new ();
  gtk_widget_show (eventbox91);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox91, 200, 256);
  gtk_widget_set_size_request (eventbox91, 88, 24);

  radiobuttonhomme1 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobuttonhomme1);
  gtk_container_add (GTK_CONTAINER (eventbox91), radiobuttonhomme1);
  gtk_widget_set_size_request (radiobuttonhomme1, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhomme1), radiobuttonfemme1_group);
  radiobuttonfemme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhomme1));

  eventbox92 = gtk_event_box_new ();
  gtk_widget_show (eventbox92);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox92, 176, 128);
  gtk_widget_set_size_request (eventbox92, 56, 22);

  label42 = gtk_label_new (_("Day:"));
  gtk_widget_show (label42);
  gtk_container_add (GTK_CONTAINER (eventbox92), label42);
  gtk_widget_set_size_request (label42, 56, 22);

  eventbox93 = gtk_event_box_new ();
  gtk_widget_show (eventbox93);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox93, 304, 128);
  gtk_widget_set_size_request (eventbox93, 52, 24);

  label43 = gtk_label_new (_("Month:"));
  gtk_widget_show (label43);
  gtk_container_add (GTK_CONTAINER (eventbox93), label43);
  gtk_widget_set_size_request (label43, 52, 24);

  eventbox94 = gtk_event_box_new ();
  gtk_widget_show (eventbox94);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox94, 424, 128);
  gtk_widget_set_size_request (eventbox94, 56, 27);

  label44 = gtk_label_new (_("Year:"));
  gtk_widget_show (label44);
  gtk_container_add (GTK_CONTAINER (eventbox94), label44);
  gtk_widget_set_size_request (label44, 59, 27);

  image6 = create_pixmap (window1, "IMG_1902.jpeg");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed3), image6, 0, 0);
  gtk_widget_set_size_request (image6, 696, 736);

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), eventbox63);

  label2 = gtk_label_new (_("    <span  font_size=\"13000\" > <span foreground=\"brown\">Modifier </span></span>"));
  gtk_widget_show (label2);
  gtk_container_add (GTK_CONTAINER (eventbox63), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  eventbox78 = gtk_event_box_new ();
  gtk_widget_show (eventbox78);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox78);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (eventbox78), fixed4);

  eventbox70 = gtk_event_box_new ();
  gtk_widget_show (eventbox70);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox70, 168, 64);
  gtk_widget_set_size_request (eventbox70, 189, 29);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_container_add (GTK_CONTAINER (eventbox70), comboboxentry1);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  eventbox72 = gtk_event_box_new ();
  gtk_widget_show (eventbox72);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox72, 64, 64);
  gtk_widget_set_size_request (eventbox72, 56, 25);

  labelID2 = gtk_label_new (_("ID"));
  gtk_widget_show (labelID2);
  gtk_container_add (GTK_CONTAINER (eventbox72), labelID2);
  gtk_widget_set_size_request (labelID2, 56, 25);

  eventbox76 = gtk_event_box_new ();
  gtk_widget_show (eventbox76);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox76, 368, 64);
  gtk_widget_set_size_request (eventbox76, 80, 32);

  actualiser = gtk_button_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (actualiser);
  gtk_container_add (GTK_CONTAINER (eventbox76), actualiser);
  gtk_widget_set_size_request (actualiser, 80, 32);

  eventbox77 = gtk_event_box_new ();
  gtk_widget_show (eventbox77);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox77, 88, 0);
  gtk_widget_set_size_request (eventbox77, 264, 40);

  label30 = gtk_label_new (_("<u><span  font_size=\"15000\" > <span foreground=\"brown\">--suprimer citoyen--</span></span></u>"));
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (eventbox77), label30);
  gtk_widget_set_size_request (label30, 264, 40);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  eventbox87 = gtk_event_box_new ();
  gtk_widget_show (eventbox87);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox87, 200, 176);
  gtk_widget_set_size_request (eventbox87, 104, 29);

  buttonsuprimer = gtk_button_new ();
  gtk_widget_show (buttonsuprimer);
  gtk_container_add (GTK_CONTAINER (eventbox87), buttonsuprimer);
  gtk_widget_set_size_request (buttonsuprimer, 104, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonsuprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  eventbox75 = gtk_event_box_new ();
  gtk_widget_show (eventbox75);
  gtk_box_pack_start (GTK_BOX (hbox3), eventbox75, FALSE, FALSE, 0);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (eventbox75), image3);

  eventbox74 = gtk_event_box_new ();
  gtk_widget_show (eventbox74);
  gtk_box_pack_start (GTK_BOX (hbox3), eventbox74, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("suprimer"));
  gtk_widget_show (label33);
  gtk_container_add (GTK_CONTAINER (eventbox74), label33);

  entrymdp2 = gtk_entry_new ();
  gtk_widget_show (entrymdp2);
  gtk_fixed_put (GTK_FIXED (fixed4), entrymdp2, 176, 112);
  gtk_widget_set_size_request (entrymdp2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp2), 8226);

  eventbox88 = gtk_event_box_new ();
  gtk_widget_show (eventbox88);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox88, 16, 120);
  gtk_widget_set_size_request (eventbox88, 136, 17);

  labelmdp = gtk_label_new (_("mot de passe"));
  gtk_widget_show (labelmdp);
  gtk_container_add (GTK_CONTAINER (eventbox88), labelmdp);
  gtk_widget_set_size_request (labelmdp, 136, 17);

  image7 = create_pixmap (window1, "IMG_1902.jpeg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed4), image7, 0, 0);
  gtk_widget_set_size_request (image7, 720, 656);

  eventbox62 = gtk_event_box_new ();
  gtk_widget_show (eventbox62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), eventbox62);

  label3 = gtk_label_new (_("<span  font_size=\"13000\" > <span foreground=\"brown\">Suprimer </span></span>"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (eventbox62), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox47);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (eventbox47), fixed5);

  entryID3 = gtk_entry_new ();
  gtk_widget_show (entryID3);
  gtk_fixed_put (GTK_FIXED (fixed5), entryID3, 152, 48);
  gtk_widget_set_size_request (entryID3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID3), 8226);

  entrymotdepasse3 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse3);
  gtk_fixed_put (GTK_FIXED (fixed5), entrymotdepasse3, 152, 80);
  gtk_widget_set_size_request (entrymotdepasse3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse3), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 8, 168);
  gtk_widget_set_size_request (treeview1, 664, 400);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox45, 64, 48);
  gtk_widget_set_size_request (eventbox45, 56, 25);

  labelID3 = gtk_label_new (_("ID"));
  gtk_widget_show (labelID3);
  gtk_container_add (GTK_CONTAINER (eventbox45), labelID3);
  gtk_widget_set_size_request (labelID3, 56, 25);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox46, 8, 80);
  gtk_widget_set_size_request (eventbox46, 121, 17);

  labelmotdepasse3 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (labelmotdepasse3);
  gtk_container_add (GTK_CONTAINER (eventbox46), labelmotdepasse3);
  gtk_widget_set_size_request (labelmotdepasse3, 121, 17);

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox48, 152, 120);
  gtk_widget_set_size_request (eventbox48, 96, 29);

  buttonafficher = gtk_button_new ();
  gtk_widget_show (buttonafficher);
  gtk_container_add (GTK_CONTAINER (eventbox48), buttonafficher);
  gtk_widget_set_size_request (buttonafficher, 96, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonafficher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox50, FALSE, FALSE, 0);

  image4 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (eventbox50), image4);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox49, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label37);
  gtk_container_add (GTK_CONTAINER (eventbox49), label37);

  eventbox83 = gtk_event_box_new ();
  gtk_widget_show (eventbox83);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox83, 72, 9);
  gtk_widget_set_size_request (eventbox83, 296, 23);

  label34 = gtk_label_new (_("<u><span  font_size=\"15000\" > <span foreground=\"brown\">--Afficher citoyen--</span></span></u>"));
  gtk_widget_show (label34);
  gtk_container_add (GTK_CONTAINER (eventbox83), label34);
  gtk_widget_set_size_request (label34, 296, 23);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  image8 = create_pixmap (window1, "IMG_1902.jpeg");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed5), image8, -32, 0);
  gtk_widget_set_size_request (image8, 720, 744);

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), eventbox61);

  label4 = gtk_label_new (_("<span  font_size=\"13000\" > <span foreground=\"brown\">Afficher </span></span>"));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (eventbox61), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox52);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (eventbox52), fixed6);

  entryID4 = gtk_entry_new ();
  gtk_widget_show (entryID4);
  gtk_fixed_put (GTK_FIXED (fixed6), entryID4, 144, 48);
  gtk_widget_set_size_request (entryID4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID4), 8226);

  entrymotdepasse4 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse4);
  gtk_fixed_put (GTK_FIXED (fixed6), entrymotdepasse4, 144, 80);
  gtk_widget_set_size_request (entrymotdepasse4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse4), 8226);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox51, 48, 16);
  gtk_widget_set_size_request (eventbox51, 296, 24);

  label38 = gtk_label_new (_("<u><span  font_size=\"15000\" > <span foreground=\"brown\">--Calculer facture  citoyen--</span></span></u>"));
  gtk_widget_show (label38);
  gtk_container_add (GTK_CONTAINER (eventbox51), label38);
  gtk_widget_set_size_request (label38, 296, 24);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox53, 8, 88);
  gtk_widget_set_size_request (eventbox53, 121, 17);

  labelmotdepasse4 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (labelmotdepasse4);
  gtk_container_add (GTK_CONTAINER (eventbox53), labelmotdepasse4);
  gtk_widget_set_size_request (labelmotdepasse4, 121, 17);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox54, 32, 56);
  gtk_widget_set_size_request (eventbox54, 49, 17);

  labelID4 = gtk_label_new (_("ID"));
  gtk_widget_show (labelID4);
  gtk_container_add (GTK_CONTAINER (eventbox54), labelID4);
  gtk_widget_set_size_request (labelID4, 49, 17);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox55, 120, 120);
  gtk_widget_set_size_request (eventbox55, 96, 29);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (eventbox55), button5);
  gtk_widget_set_size_request (button5, 96, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox57, FALSE, FALSE, 0);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (eventbox57), image5);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox56, FALSE, FALSE, 0);

  labelvalider = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (labelvalider);
  gtk_container_add (GTK_CONTAINER (eventbox56), labelvalider);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox58, 16, 168);
  gtk_widget_set_size_request (eventbox58, 192, 25);

  labelfa = gtk_label_new (_("<span  font_size=\"15000\" > <span foreground=\"brown\">-- facture  --</span></span>"));
  gtk_widget_show (labelfa);
  gtk_container_add (GTK_CONTAINER (eventbox58), labelfa);
  gtk_widget_set_size_request (labelfa, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelfa), TRUE);

  eventbox84 = gtk_event_box_new ();
  gtk_widget_show (eventbox84);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox84, 64, 232);
  gtk_widget_set_size_request (eventbox84, 568, 48);

  tot = gtk_label_new ("");
  gtk_widget_show (tot);
  gtk_container_add (GTK_CONTAINER (eventbox84), tot);
  gtk_widget_set_size_request (tot, 568, 48);
  gtk_label_set_use_markup (GTK_LABEL (tot), TRUE);

  image9 = create_pixmap (window1, "IMG_1902.jpeg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed6), image9, 0, 0);
  gtk_widget_set_size_request (image9, 688, 648);

  eventbox60 = gtk_event_box_new ();
  gtk_widget_show (eventbox60);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), eventbox60);

  label5 = gtk_label_new (_("<span  font_size=\"13000\" > <span foreground=\"brown\">Facture </span></span>"));
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (eventbox60), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  g_signal_connect ((gpointer) radiobuttonfemme, "toggled",
                    G_CALLBACK (on_radiobuttonfemme_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonhomme, "toggled",
                    G_CALLBACK (on_radiobuttonhomme_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfemme1, "toggled",
                    G_CALLBACK (on_radiobuttonfemme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonhomme1, "toggled",
                    G_CALLBACK (on_radiobuttonhomme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuprimer, "clicked",
                    G_CALLBACK (on_buttonsuprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher, "clicked",
                    G_CALLBACK (on_buttonafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, eventbox89, "eventbox89");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (window1, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (window1, entryID, "entryID");
  GLADE_HOOKUP_OBJECT (window1, entrymdp, "entrymdp");
  GLADE_HOOKUP_OBJECT (window1, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (window1, entryemail, "entryemail");
  GLADE_HOOKUP_OBJECT (window1, entrymatricule, "entrymatricule");
  GLADE_HOOKUP_OBJECT (window1, entrytype, "entrytype");
  GLADE_HOOKUP_OBJECT (window1, day, "day");
  GLADE_HOOKUP_OBJECT (window1, month, "month");
  GLADE_HOOKUP_OBJECT (window1, year, "year");
  GLADE_HOOKUP_OBJECT (window1, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window1, labelnomm, "labelnomm");
  GLADE_HOOKUP_OBJECT (window1, labelmdpm, "labelmdpm");
  GLADE_HOOKUP_OBJECT (window1, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (window1, radiobuttonfemme, "radiobuttonfemme");
  GLADE_HOOKUP_OBJECT (window1, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (window1, labeltypedevoiture, "labeltypedevoiture");
  GLADE_HOOKUP_OBJECT (window1, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (window1, labeldate_de_naissace, "labeldate_de_naissace");
  GLADE_HOOKUP_OBJECT (window1, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (window1, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (window1, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (window1, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (window1, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (window1, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (window1, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (window1, labelmotdepasse, "labelmotdepasse");
  GLADE_HOOKUP_OBJECT (window1, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (window1, labeladresse, "labeladresse");
  GLADE_HOOKUP_OBJECT (window1, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (window1, labelemail, "labelemail");
  GLADE_HOOKUP_OBJECT (window1, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (window1, labelsexe, "labelsexe");
  GLADE_HOOKUP_OBJECT (window1, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (window1, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (window1, labelmatricule, "labelmatricule");
  GLADE_HOOKUP_OBJECT (window1, eventbox85, "eventbox85");
  GLADE_HOOKUP_OBJECT (window1, radiobuttonhomme, "radiobuttonhomme");
  GLADE_HOOKUP_OBJECT (window1, eventbox95, "eventbox95");
  GLADE_HOOKUP_OBJECT (window1, labelprenomm, "labelprenomm");
  GLADE_HOOKUP_OBJECT (window1, eventbox96, "eventbox96");
  GLADE_HOOKUP_OBJECT (window1, labelidm, "labelidm");
  GLADE_HOOKUP_OBJECT (window1, eventbox97, "eventbox97");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, eventbox98, "eventbox98");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, eventbox99, "eventbox99");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entrynom1, "entrynom1");
  GLADE_HOOKUP_OBJECT (window1, entryprenom1, "entryprenom1");
  GLADE_HOOKUP_OBJECT (window1, entryID1, "entryID1");
  GLADE_HOOKUP_OBJECT (window1, entryemail1, "entryemail1");
  GLADE_HOOKUP_OBJECT (window1, entryadresse1, "entryadresse1");
  GLADE_HOOKUP_OBJECT (window1, entrymatricule1, "entrymatricule1");
  GLADE_HOOKUP_OBJECT (window1, entrymotdepasse1, "entrymotdepasse1");
  GLADE_HOOKUP_OBJECT (window1, entrytypedevoiture1, "entrytypedevoiture1");
  GLADE_HOOKUP_OBJECT (window1, day1, "day1");
  GLADE_HOOKUP_OBJECT (window1, month1, "month1");
  GLADE_HOOKUP_OBJECT (window1, year1, "year1");
  GLADE_HOOKUP_OBJECT (window1, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (window1, labelnom1, "labelnom1");
  GLADE_HOOKUP_OBJECT (window1, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (window1, labelprenom1, "labelprenom1");
  GLADE_HOOKUP_OBJECT (window1, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (window1, labelID1, "labelID1");
  GLADE_HOOKUP_OBJECT (window1, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (window1, labeldatedenaissance1, "labeldatedenaissance1");
  GLADE_HOOKUP_OBJECT (window1, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (window1, labelemail1, "labelemail1");
  GLADE_HOOKUP_OBJECT (window1, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (window1, labeladressse1, "labeladressse1");
  GLADE_HOOKUP_OBJECT (window1, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (window1, labelmatricule1, "labelmatricule1");
  GLADE_HOOKUP_OBJECT (window1, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (window1, labelsexe1, "labelsexe1");
  GLADE_HOOKUP_OBJECT (window1, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (window1, labelmotdepasse1, "labelmotdepasse1");
  GLADE_HOOKUP_OBJECT (window1, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (window1, labeltypedevoiture1, "labeltypedevoiture1");
  GLADE_HOOKUP_OBJECT (window1, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (window1, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (window1, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, eventbox90, "eventbox90");
  GLADE_HOOKUP_OBJECT (window1, radiobuttonfemme1, "radiobuttonfemme1");
  GLADE_HOOKUP_OBJECT (window1, eventbox91, "eventbox91");
  GLADE_HOOKUP_OBJECT (window1, radiobuttonhomme1, "radiobuttonhomme1");
  GLADE_HOOKUP_OBJECT (window1, eventbox92, "eventbox92");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, eventbox93, "eventbox93");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, eventbox94, "eventbox94");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, eventbox78, "eventbox78");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, eventbox70, "eventbox70");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window1, eventbox72, "eventbox72");
  GLADE_HOOKUP_OBJECT (window1, labelID2, "labelID2");
  GLADE_HOOKUP_OBJECT (window1, eventbox76, "eventbox76");
  GLADE_HOOKUP_OBJECT (window1, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (window1, eventbox77, "eventbox77");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, eventbox87, "eventbox87");
  GLADE_HOOKUP_OBJECT (window1, buttonsuprimer, "buttonsuprimer");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, eventbox75, "eventbox75");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, eventbox74, "eventbox74");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, entrymdp2, "entrymdp2");
  GLADE_HOOKUP_OBJECT (window1, eventbox88, "eventbox88");
  GLADE_HOOKUP_OBJECT (window1, labelmdp, "labelmdp");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, eventbox62, "eventbox62");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, entryID3, "entryID3");
  GLADE_HOOKUP_OBJECT (window1, entrymotdepasse3, "entrymotdepasse3");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (window1, labelID3, "labelID3");
  GLADE_HOOKUP_OBJECT (window1, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (window1, labelmotdepasse3, "labelmotdepasse3");
  GLADE_HOOKUP_OBJECT (window1, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (window1, buttonafficher, "buttonafficher");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, eventbox83, "eventbox83");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, entryID4, "entryID4");
  GLADE_HOOKUP_OBJECT (window1, entrymotdepasse4, "entrymotdepasse4");
  GLADE_HOOKUP_OBJECT (window1, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (window1, labelmotdepasse4, "labelmotdepasse4");
  GLADE_HOOKUP_OBJECT (window1, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (window1, labelID4, "labelID4");
  GLADE_HOOKUP_OBJECT (window1, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (window1, labelvalider, "labelvalider");
  GLADE_HOOKUP_OBJECT (window1, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (window1, labelfa, "labelfa");
  GLADE_HOOKUP_OBJECT (window1, eventbox84, "eventbox84");
  GLADE_HOOKUP_OBJECT (window1, tot, "tot");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, eventbox60, "eventbox60");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");

  return window1;
}

